"""Finnhub financials provider — US company financial statements.

Uses Finnhub API for US company financial data.
Free tier: 60 calls/minute.

Uses financials-reported endpoint (FREE) instead of financials endpoint (PAID).
Returns three statements:
- income statement (利润表)
- balance sheet (资产负债表)  
- cash flow statement (现金流量表)
"""
from __future__ import annotations

import logging
import time

import pandas as pd
import requests

from ..capabilities.base import Evidence
from ..capabilities.financials import FinancialsCapability, StatementType
from ..config import CONFIG

log = logging.getLogger(__name__)

_FINNHUB_BASE = "https://finnhub.io/api/v1"
_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36"
    ),
}

# Statement type mapping
_STATEMENT_MAP: dict[StatementType, str] = {
    "income": "ic",      # Income Statement
    "balance": "bs",     # Balance Sheet
    "cashflow": "cf",    # Cash Flow
}

_STATEMENT_ZH: dict[StatementType, str] = {
    "income": "利润表",
    "balance": "资产负债表",
    "cashflow": "现金流量表",
}

# Key fields to display (Finnhub field names from financials-reported)
# These match the actual labels returned by Finnhub API
_DISPLAY_COLS: dict[StatementType, list[str]] = {
    "income": [
        "Revenue from Contract with Customer, Excluding Assessed Tax",
        "Cost of Goods and Services Sold",
        "Gross Profit",
        "Research and Development Expense",
        "Selling and Marketing Expense",
        "General and Administrative Expense",
        "Operating Income (Loss)",
        "Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest",
        "Income Tax Expense (Benefit)",
        "Net income",
        "Basic (A/B)",
        "Earnings Per Share, Diluted",
    ],
    "balance": [
        "Cash and Cash Equivalents, at Carrying Value",
        "Short-Term Investments",
        "Cash, Cash Equivalents, and Short-Term Investments",
        "Accounts Receivable, after Allowance for Credit Loss, Current",
        "Inventory, Net",
        "Other current assets",
        "Assets, Current",
        "Property, Plant and Equipment, Net",
        "Operating Lease, Right-of-Use Asset",
        "Long-Term Investments",
        "Goodwill",
        "Finite-Lived Intangible Assets, Net",
        "Other long-term assets",
        "Assets",
        "Accounts Payable, Current",
        "Commercial Paper",
        "Long-Term Debt, Current Maturities",
        "Employee-related Liabilities, Current",
        "Accrued Income Taxes, Current",
        "Contract with Customer, Liability, Current",
        "Other current liabilities",
        "Liabilities, Current",
        "Long-Term Debt, Excluding Current Maturities",
        "Accrued Income Taxes, Noncurrent",
        "Contract with Customer, Liability, Noncurrent",
        "Deferred Income Tax Liabilities, Net",
        "Operating Lease, Liability, Noncurrent",
        "Other long-term liabilities",
        "Liabilities",
        "Common Stocks, Including Additional Paid in Capital",
        "Retained Earnings (Accumulated Deficit)",
        "Accumulated Other Comprehensive Income (Loss), Net of Tax",
        "Equity, Attributable to Parent",
        "Liabilities and Equity",
    ],
    "cashflow": [
        "Net income",
        "Depreciation and amortization",
        "Share-based compensation expense",
        "Cash generated by operating activities",
        "Purchases of marketable securities",
        "Cash generated by investing activities",
        "Payments for dividends and dividend equivalents",
        "Repurchases of common stock",
        "Cash used in financing activities",
    ],
}

# Chinese labels for display
_FIELD_LABELS: dict[str, str] = {
    "Revenue from Contract with Customer, Excluding Assessed Tax": "营业收入",
    "Cost of Goods and Services Sold": "销售成本",
    "Gross Profit": "毛利润",
    "Research and Development Expense": "研发费用",
    "Selling and Marketing Expense": "销售及营销费用",
    "General and Administrative Expense": "一般及管理费用",
    "Operating Income (Loss)": "营业利润",
    "Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest": "税前利润",
    "Income Tax Expense (Benefit)": "所得税费用",
    "Net income": "净利润",
    "Basic (A/B)": "基本每股收益",
    "Earnings Per Share, Diluted": "稀释每股收益",
    "Cash and Cash Equivalents, at Carrying Value": "现金及现金等价物",
    "Short-Term Investments": "短期投资",
    "Cash, Cash Equivalents, and Short-Term Investments": "现金及短期投资",
    "Accounts Receivable, after Allowance for Credit Loss, Current": "应收账款",
    "Inventory, Net": "存货",
    "Other current assets": "其他流动资产",
    "Assets, Current": "流动资产总计",
    "Property, Plant and Equipment, Net": "固定资产",
    "Operating Lease, Right-of-Use Asset": "使用权资产",
    "Long-Term Investments": "长期投资",
    "Goodwill": "商誉",
    "Finite-Lived Intangible Assets, Net": "无形资产",
    "Other long-term assets": "其他非流动资产",
    "Assets": "总资产",
    "Accounts Payable, Current": "应付账款",
    "Commercial Paper": "商业票据",
    "Long-Term Debt, Current Maturities": "长期债务当期部分",
    "Employee-related Liabilities, Current": "应付职工薪酬",
    "Accrued Income Taxes, Current": "应交所得税",
    "Contract with Customer, Liability, Current": "合同负债",
    "Other current liabilities": "其他流动负债",
    "Liabilities, Current": "流动负债总计",
    "Long-Term Debt, Excluding Current Maturities": "长期债务",
    "Accrued Income Taxes, Noncurrent": "递延所得税负债",
    "Contract with Customer, Liability, Noncurrent": "非流动合同负债",
    "Deferred Income Tax Liabilities, Net": "递延所得税负债净额",
    "Operating Lease, Liability, Noncurrent": "租赁负债",
    "Other long-term liabilities": "其他非流动负债",
    "Liabilities": "总负债",
    "Common Stocks, Including Additional Paid in Capital": "普通股及资本公积",
    "Retained Earnings (Accumulated Deficit)": "留存收益",
    "Accumulated Other Comprehensive Income (Loss), Net of Tax": "其他综合收益",
    "Equity, Attributable to Parent": "归属于母公司股东权益",
    "Liabilities and Equity": "负债及股东权益总计",
    "Depreciation and amortization": "折旧与摊销",
    "Share-based compensation expense": "股权激励费用",
    "Cash generated by operating activities": "经营活动现金流",
    "Purchases of marketable securities": "有价证券购买",
    "Cash generated by investing activities": "投资活动现金流",
    "Payments for dividends and dividend equivalents": "股息支付",
    "Repurchases of common stock": "股票回购",
    "Cash used in financing activities": "融资活动现金流",
}


class FinnhubFinancialsProvider(FinancialsCapability):
    """US Financial statements via Finnhub API (Free Tier)."""

    def __init__(
        self,
        *,
        session: requests.Session | None = None,
        request_gap_sec: float = 1.0,
        token: str | None = None,
    ):
        self._session = session or requests.Session()
        self._session.headers.update(_HEADERS)
        self._request_gap = request_gap_sec
        self._token = token or CONFIG.finnhub_api_key
        if not self._token:
            raise RuntimeError("Finnhub API key is required. Set FINNHUB_API_KEY in .env")

    def _throttle(self) -> None:
        if self._request_gap > 0:
            time.sleep(self._request_gap)

    def _fetch_financials_reported(
        self,
        symbol: str,
    ) -> list[dict]:
        """Fetch financial statements from Finnhub (FREE endpoint).
        
        Uses /stock/financials-reported which is free.
        Returns list of reports with bs, ic, cf data.
        """
        url = f"{_FINNHUB_BASE}/stock/financials-reported"
        params = {
            "symbol": symbol,
            "token": self._token,
        }
        
        try:
            r = self._session.get(url, params=params, timeout=15)
            r.raise_for_status()
            data = r.json()
            
            # Returns {"cik": "...", "data": [...], "symbol": "..."}
            return data.get("data", [])
        except Exception as e:
            log.warning("Finnhub financials-reported failed for %s: %s", symbol, e)
            return []

    def _extract_statement(
        self,
        reports: list[dict],
        statement_type: str,
    ) -> pd.DataFrame:
        """Extract a specific statement from reports."""
        rows = []
        
        for report in reports:
            report_data = report.get("report", {})
            statement_data = report_data.get(statement_type, [])
            
            if not statement_data:
                continue
            
            # Build row from statement items
            row = {
                "reportDate": report.get("endDate", ""),
                "form": report.get("form", ""),
                "year": report.get("year", ""),
                "quarter": report.get("quarter", ""),
            }
            
            for item in statement_data:
                label = item.get("label", "")
                value = item.get("value", 0)
                if label:
                    row[label] = value
            
            rows.append(row)
        
        df = pd.DataFrame(rows)
        if not df.empty and "reportDate" in df.columns:
            df = df.sort_values("reportDate", ascending=False)
        
        return df

    def get_statement(
        self,
        symbol: str,
        statement_type: StatementType,
        *,
        periods: int = 3,
    ) -> pd.DataFrame:
        """Get a financial statement (income/balance/cashflow)."""
        try:
            reports = self._fetch_financials_reported(symbol)
            self._throttle()
        except Exception as e:
            log.warning("Failed to fetch financials for %s: %s", symbol, e)
            return pd.DataFrame()
        
        if not reports:
            return pd.DataFrame()
        
        stmt_code = _STATEMENT_MAP[statement_type]
        df = self._extract_statement(reports, stmt_code)
        
        if df.empty:
            return df
        
        return df.head(periods).reset_index(drop=True)

    def summarize_statement(
        self,
        symbol: str,
        statement_type: StatementType,
        *,
        periods: int = 3,
    ) -> Evidence:
        """Produce a Markdown summary of a US financial statement (in Chinese)."""
        df = self.get_statement(symbol, statement_type, periods=periods)
        if df is None or df.empty:
            raise RuntimeError(f"no {statement_type} data for {symbol}")

        # Project to a stable subset of columns for readability.
        cols = [c for c in _DISPLAY_COLS[statement_type] if c in df.columns]
        view = df[cols] if cols else df
        
        # Rename columns to Chinese
        view = view.rename(columns=_FIELD_LABELS)

        md = (
            f"**{symbol} {_STATEMENT_ZH[statement_type]} — 最近 {len(view)} 期 (Finnhub)**\n\n"
            + view.to_markdown(index=False)
        )
        return Evidence(
            text=md,
            source_kind="financials",
            url=f"https://finnhub.io/api/v1/stock/financials-reported?symbol={symbol}",
            title=f"{symbol} {_STATEMENT_ZH[statement_type]}",
            publisher="Finnhub",
            meta={"symbol": symbol, "kind": statement_type, "periods": int(len(view))},
        )

    def collect_all(
        self,
        symbol: str,
        *,
        statement_types: list[StatementType] | None = None,
        periods: int = 3,
    ) -> list[Evidence]:
        """Collect summaries for multiple statement types."""
        types = statement_types or ["income", "balance", "cashflow"]
        out: list[Evidence] = []
        for t in types:
            try:
                ev = self.summarize_statement(symbol, t, periods=periods)
                out.append(ev)
            except Exception as e:
                log.warning("financial %s/%s failed: %s", symbol, t, e)
        return out
